excludes:
  scopes:
    - pattern: 'devDependencies'
      reason: 'DEV_DEPENDENCY_OF'
      comment: 'Packages for development only.'

curations:
  packages:
    - id: 'NPM::posthog-js:1.255.1'
      curations:
        comment: 'Based on GitHub repository, this package is Apache License 2.0'
        homepage: 'https://posthog.com'
        is_modified: false
        vcs:
          type: 'Git'
          url: 'https://github.com/posthog/posthog-js'
          revision: 'main'
        concluded_license: 'Apache-2.0'
        declared_license_mapping:
          'NOASSERTION': 'Apache-2.0'
