excludes:
  paths:
    - pattern: '**/init.gradle.kts'
      reason: 'BUILD_TOOL_OF'
      comment: 'This is an ORT helper script and not part of the project.'
  scopes:
    - pattern: 'devDependencies'
      reason: 'DEV_DEPENDENCY_OF'
      comment: 'Packages for development only.'
