/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SsoFailCallbackRouteImport } from './routes/sso-fail-callback'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SignupPageRouteImport } from './routes/signup-page'
import { Route as LoginPageRouteImport } from './routes/login-page'
import { Route as NotFoundRouteImport } from './routes/$not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstrumentsIndexRouteImport } from './routes/instruments/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoFailCallbackRoute = SsoFailCallbackRouteImport.update({
  id: '/sso-fail-callback',
  path: '/sso-fail-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPageRoute = SignupPageRouteImport.update({
  id: '/signup-page',
  path: '/signup-page',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/login-page',
  path: '/login-page',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/$not-found',
  path: '/$not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsIndexRoute = InstrumentsIndexRouteImport.update({
  id: '/instruments/',
  path: '/instruments/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/login-page': typeof LoginPageRoute
  '/signup-page': typeof SignupPageRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/sso-fail-callback': typeof SsoFailCallbackRoute
  '/verify-email': typeof VerifyEmailRoute
  '/instruments': typeof InstrumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/login-page': typeof LoginPageRoute
  '/signup-page': typeof SignupPageRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/sso-fail-callback': typeof SsoFailCallbackRoute
  '/verify-email': typeof VerifyEmailRoute
  '/instruments': typeof InstrumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/login-page': typeof LoginPageRoute
  '/signup-page': typeof SignupPageRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/sso-fail-callback': typeof SsoFailCallbackRoute
  '/verify-email': typeof VerifyEmailRoute
  '/instruments/': typeof InstrumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$not-found'
    | '/login-page'
    | '/signup-page'
    | '/sso-callback'
    | '/sso-fail-callback'
    | '/verify-email'
    | '/instruments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$not-found'
    | '/login-page'
    | '/signup-page'
    | '/sso-callback'
    | '/sso-fail-callback'
    | '/verify-email'
    | '/instruments'
  id:
    | '__root__'
    | '/'
    | '/$not-found'
    | '/login-page'
    | '/signup-page'
    | '/sso-callback'
    | '/sso-fail-callback'
    | '/verify-email'
    | '/instruments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  LoginPageRoute: typeof LoginPageRoute
  SignupPageRoute: typeof SignupPageRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  SsoFailCallbackRoute: typeof SsoFailCallbackRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InstrumentsIndexRoute: typeof InstrumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-fail-callback': {
      id: '/sso-fail-callback'
      path: '/sso-fail-callback'
      fullPath: '/sso-fail-callback'
      preLoaderRoute: typeof SsoFailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-page': {
      id: '/signup-page'
      path: '/signup-page'
      fullPath: '/signup-page'
      preLoaderRoute: typeof SignupPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-page': {
      id: '/login-page'
      path: '/login-page'
      fullPath: '/login-page'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$not-found': {
      id: '/$not-found'
      path: '/$not-found'
      fullPath: '/$not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/': {
      id: '/instruments/'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof InstrumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  LoginPageRoute: LoginPageRoute,
  SignupPageRoute: SignupPageRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  SsoFailCallbackRoute: SsoFailCallbackRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InstrumentsIndexRoute: InstrumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
