/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/$not-found'
import { Route as LegalRouteRouteImport } from './routes/_legal/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsOfServiceRouteImport } from './routes/_legal/terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/_legal/privacy-policy'
import { Route as LegalFaqRouteImport } from './routes/_legal/faq'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSsoCallbackRouteImport } from './routes/_auth/sso-callback'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLogoutRouteImport } from './routes/_auth/logout'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthedTransactionsRouteRouteImport } from './routes/_authed/transactions/route'
import { Route as AuthedStrategiesRouteRouteImport } from './routes/_authed/strategies/route'
import { Route as AuthedStatisticsRouteRouteImport } from './routes/_authed/statistics/route'
import { Route as AuthedInstrumentsRouteRouteImport } from './routes/_authed/instruments/route'
import { Route as AuthedTransactionsIndexRouteImport } from './routes/_authed/transactions/index'
import { Route as AuthedStrategiesIndexRouteImport } from './routes/_authed/strategies/index'
import { Route as AuthedStatisticsIndexRouteImport } from './routes/_authed/statistics/index'
import { Route as AuthedInstrumentsIndexRouteImport } from './routes/_authed/instruments/index'
import { Route as AuthedInstrumentsInstrumentIdRouteImport } from './routes/_authed/instruments/$instrumentId'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/$not-found',
  path: '/$not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalFaqRoute = LegalFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LegalRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthedTransactionsRouteRoute = AuthedTransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedStrategiesRouteRoute = AuthedStrategiesRouteRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedStatisticsRouteRoute = AuthedStatisticsRouteRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInstrumentsRouteRoute = AuthedInstrumentsRouteRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTransactionsIndexRoute = AuthedTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedTransactionsRouteRoute,
} as any)
const AuthedStrategiesIndexRoute = AuthedStrategiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedStrategiesRouteRoute,
} as any)
const AuthedStatisticsIndexRoute = AuthedStatisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedStatisticsRouteRoute,
} as any)
const AuthedInstrumentsIndexRoute = AuthedInstrumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedInstrumentsRouteRoute,
} as any)
const AuthedInstrumentsInstrumentIdRoute =
  AuthedInstrumentsInstrumentIdRouteImport.update({
    id: '/$instrumentId',
    path: '/$instrumentId',
    getParentRoute: () => AuthedInstrumentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/instruments': typeof AuthedInstrumentsRouteRouteWithChildren
  '/statistics': typeof AuthedStatisticsRouteRouteWithChildren
  '/strategies': typeof AuthedStrategiesRouteRouteWithChildren
  '/transactions': typeof AuthedTransactionsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/signup': typeof AuthSignupRoute
  '/sso-callback': typeof AuthSsoCallbackRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/faq': typeof LegalFaqRoute
  '/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/terms-of-service': typeof LegalTermsOfServiceRoute
  '/instruments/$instrumentId': typeof AuthedInstrumentsInstrumentIdRoute
  '/instruments/': typeof AuthedInstrumentsIndexRoute
  '/statistics/': typeof AuthedStatisticsIndexRoute
  '/strategies/': typeof AuthedStrategiesIndexRoute
  '/transactions/': typeof AuthedTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/signup': typeof AuthSignupRoute
  '/sso-callback': typeof AuthSsoCallbackRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/faq': typeof LegalFaqRoute
  '/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/terms-of-service': typeof LegalTermsOfServiceRoute
  '/instruments/$instrumentId': typeof AuthedInstrumentsInstrumentIdRoute
  '/instruments': typeof AuthedInstrumentsIndexRoute
  '/statistics': typeof AuthedStatisticsIndexRoute
  '/strategies': typeof AuthedStrategiesIndexRoute
  '/transactions': typeof AuthedTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_legal': typeof LegalRouteRouteWithChildren
  '/$not-found': typeof NotFoundRoute
  '/_authed/instruments': typeof AuthedInstrumentsRouteRouteWithChildren
  '/_authed/statistics': typeof AuthedStatisticsRouteRouteWithChildren
  '/_authed/strategies': typeof AuthedStrategiesRouteRouteWithChildren
  '/_authed/transactions': typeof AuthedTransactionsRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/sso-callback': typeof AuthSsoCallbackRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_legal/faq': typeof LegalFaqRoute
  '/_legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/_legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/_authed/instruments/$instrumentId': typeof AuthedInstrumentsInstrumentIdRoute
  '/_authed/instruments/': typeof AuthedInstrumentsIndexRoute
  '/_authed/statistics/': typeof AuthedStatisticsIndexRoute
  '/_authed/strategies/': typeof AuthedStrategiesIndexRoute
  '/_authed/transactions/': typeof AuthedTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$not-found'
    | '/instruments'
    | '/statistics'
    | '/strategies'
    | '/transactions'
    | '/login'
    | '/logout'
    | '/signup'
    | '/sso-callback'
    | '/verify-email'
    | '/faq'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/instruments/$instrumentId'
    | '/instruments/'
    | '/statistics/'
    | '/strategies/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$not-found'
    | '/login'
    | '/logout'
    | '/signup'
    | '/sso-callback'
    | '/verify-email'
    | '/faq'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/instruments/$instrumentId'
    | '/instruments'
    | '/statistics'
    | '/strategies'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authed'
    | '/_legal'
    | '/$not-found'
    | '/_authed/instruments'
    | '/_authed/statistics'
    | '/_authed/strategies'
    | '/_authed/transactions'
    | '/_auth/login'
    | '/_auth/logout'
    | '/_auth/signup'
    | '/_auth/sso-callback'
    | '/_auth/verify-email'
    | '/_legal/faq'
    | '/_legal/privacy-policy'
    | '/_legal/terms-of-service'
    | '/_authed/instruments/$instrumentId'
    | '/_authed/instruments/'
    | '/_authed/statistics/'
    | '/_authed/strategies/'
    | '/_authed/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$not-found': {
      id: '/$not-found'
      path: '/$not-found'
      fullPath: '/$not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal/terms-of-service': {
      id: '/_legal/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_legal/privacy-policy': {
      id: '/_legal/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_legal/faq': {
      id: '/_legal/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LegalFaqRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sso-callback': {
      id: '/_auth/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/strategies': {
      id: '/_authed/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthedStrategiesRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/statistics': {
      id: '/_authed/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthedStatisticsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/instruments': {
      id: '/_authed/instruments'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof AuthedInstrumentsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/transactions/': {
      id: '/_authed/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthedTransactionsIndexRouteImport
      parentRoute: typeof AuthedTransactionsRouteRoute
    }
    '/_authed/strategies/': {
      id: '/_authed/strategies/'
      path: '/'
      fullPath: '/strategies/'
      preLoaderRoute: typeof AuthedStrategiesIndexRouteImport
      parentRoute: typeof AuthedStrategiesRouteRoute
    }
    '/_authed/statistics/': {
      id: '/_authed/statistics/'
      path: '/'
      fullPath: '/statistics/'
      preLoaderRoute: typeof AuthedStatisticsIndexRouteImport
      parentRoute: typeof AuthedStatisticsRouteRoute
    }
    '/_authed/instruments/': {
      id: '/_authed/instruments/'
      path: '/'
      fullPath: '/instruments/'
      preLoaderRoute: typeof AuthedInstrumentsIndexRouteImport
      parentRoute: typeof AuthedInstrumentsRouteRoute
    }
    '/_authed/instruments/$instrumentId': {
      id: '/_authed/instruments/$instrumentId'
      path: '/$instrumentId'
      fullPath: '/instruments/$instrumentId'
      preLoaderRoute: typeof AuthedInstrumentsInstrumentIdRouteImport
      parentRoute: typeof AuthedInstrumentsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedInstrumentsRouteRouteChildren {
  AuthedInstrumentsInstrumentIdRoute: typeof AuthedInstrumentsInstrumentIdRoute
  AuthedInstrumentsIndexRoute: typeof AuthedInstrumentsIndexRoute
}

const AuthedInstrumentsRouteRouteChildren: AuthedInstrumentsRouteRouteChildren =
  {
    AuthedInstrumentsInstrumentIdRoute: AuthedInstrumentsInstrumentIdRoute,
    AuthedInstrumentsIndexRoute: AuthedInstrumentsIndexRoute,
  }

const AuthedInstrumentsRouteRouteWithChildren =
  AuthedInstrumentsRouteRoute._addFileChildren(
    AuthedInstrumentsRouteRouteChildren,
  )

interface AuthedStatisticsRouteRouteChildren {
  AuthedStatisticsIndexRoute: typeof AuthedStatisticsIndexRoute
}

const AuthedStatisticsRouteRouteChildren: AuthedStatisticsRouteRouteChildren = {
  AuthedStatisticsIndexRoute: AuthedStatisticsIndexRoute,
}

const AuthedStatisticsRouteRouteWithChildren =
  AuthedStatisticsRouteRoute._addFileChildren(
    AuthedStatisticsRouteRouteChildren,
  )

interface AuthedStrategiesRouteRouteChildren {
  AuthedStrategiesIndexRoute: typeof AuthedStrategiesIndexRoute
}

const AuthedStrategiesRouteRouteChildren: AuthedStrategiesRouteRouteChildren = {
  AuthedStrategiesIndexRoute: AuthedStrategiesIndexRoute,
}

const AuthedStrategiesRouteRouteWithChildren =
  AuthedStrategiesRouteRoute._addFileChildren(
    AuthedStrategiesRouteRouteChildren,
  )

interface AuthedTransactionsRouteRouteChildren {
  AuthedTransactionsIndexRoute: typeof AuthedTransactionsIndexRoute
}

const AuthedTransactionsRouteRouteChildren: AuthedTransactionsRouteRouteChildren =
  {
    AuthedTransactionsIndexRoute: AuthedTransactionsIndexRoute,
  }

const AuthedTransactionsRouteRouteWithChildren =
  AuthedTransactionsRouteRoute._addFileChildren(
    AuthedTransactionsRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedInstrumentsRouteRoute: typeof AuthedInstrumentsRouteRouteWithChildren
  AuthedStatisticsRouteRoute: typeof AuthedStatisticsRouteRouteWithChildren
  AuthedStrategiesRouteRoute: typeof AuthedStrategiesRouteRouteWithChildren
  AuthedTransactionsRouteRoute: typeof AuthedTransactionsRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedInstrumentsRouteRoute: AuthedInstrumentsRouteRouteWithChildren,
  AuthedStatisticsRouteRoute: AuthedStatisticsRouteRouteWithChildren,
  AuthedStrategiesRouteRoute: AuthedStrategiesRouteRouteWithChildren,
  AuthedTransactionsRouteRoute: AuthedTransactionsRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface LegalRouteRouteChildren {
  LegalFaqRoute: typeof LegalFaqRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalFaqRoute: LegalFaqRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
