// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Serializer for AccountValueSnapshot model.
 */
export type AccountValueSnapshotDaily = {
    /**
     * Date of the value measurement
     */
    readonly date: string;
    /**
     * Account value on this date
     */
    value: number;
};

export type AssetAllocation = {
    total_value: number;
    total_gain_this_year: number;
    allocations: Array<AssetAllocationItem>;
};

export type AssetAllocationItem = {
    instrument_name: string;
    instrument_ticker: string;
    instrument_logo: string | null;
    instrument_icon: string | null;
    value: number;
    percentage: number;
};

/**
 * Serializer for authentication test response
 */
export type AuthTestResponse = {
    /**
     * Authentication success message
     */
    message: string;
    /**
     * Role of the authenticated user
     */
    user_role: string;
    /**
     * ID of the authenticated user
     */
    user_id: number;
};

export type ClerkLoginRequest = {
    email: string;
    password: string;
};

export type CreateMarketOrderRequest = {
    ticker: string;
    volume: string;
    is_buy: boolean;
};

export type CurrentAccountValue = {
    total_account_value: number;
    gain: number;
    gain_percentage: number | null;
};

export type HistoryEntry = {
    /**
     * Date of the transaction
     */
    timestamp: string;
    /**
     * True if the transaction was a buy False if it was a sell
     */
    is_buy: boolean;
    /**
     * Number of shares traded
     */
    quantity: number;
    /**
     * Price per share at the time of transaction
     */
    share_price: number;
    /**
     * Acquisition price (null for SELL transactions)
     */
    acquisition_price: number | null;
};

export type Insight = {
    sentiment?: string | null;
    sentiment_reasoning?: string | null;
    ticker?: string | null;
};

export type InstrumentList = {
    readonly id: string;
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active: boolean;
    name: string;
    market: MarketEnum;
    market_cap?: string | null;
    currency_name: string;
    icon?: string | null;
    logo?: string | null;
};

export type InstrumentName = {
    /**
     * Ticker Symbol
     */
    ticker: string;
};

export type InstrumentRetrieve = {
    readonly id: string;
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active: boolean;
    name: string;
    /**
     * Central Index Key assigned by the SEC.
     */
    cik?: string | null;
    market: MarketEnum;
    market_cap?: string | null;
    /**
     * Composite Financial Instrument Global Identifier.
     */
    composite_figi?: string | null;
    currency_name: string;
    /**
     * Locale where the ticker is traded, e.g. 'US'.
     *
     * * `us` - United States
     * * `global` - Global
     */
    locale: LocaleEnum;
    /**
     * Code of the primary exchange where the ticker is traded.
     */
    primary_exchange?: string | null;
    share_class_figi?: string | null;
    description?: string | null;
    /**
     * Base symbol for related tickers.
     */
    ticker_root?: string | null;
    /**
     * Suffix for ticker if applicable.
     */
    ticker_suffix?: string | null;
    homepage_url?: string | null;
    /**
     * Date when the ticker was first listed.
     */
    list_date?: string | null;
    phone_number?: string | null;
    /**
     * Shares Outstanding (Share Class)
     * Number of shares outstanding for this share class.
     */
    share_class_shares_outstanding?: number | null;
    /**
     * Standard Industrial Classification code.
     */
    sic_code?: string | null;
    sic_description?: string | null;
    total_employees?: number | null;
    weighted_shares_outstanding?: number | null;
    readonly address: {
        address1: string | null;
        address2: string | null;
        city: string | null;
        state: string | null;
        postal_code: string | null;
    };
    icon?: string | null;
    logo?: string | null;
};

export type InstrumentWithPrice = {
    readonly id: string;
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active: boolean;
    name: string;
    market: MarketEnum;
    market_cap?: string | null;
    currency_name: string;
    icon?: string | null;
    logo?: string | null;
    price_info: PriceDailySummary;
};

export type Investor = {
    readonly id: string;
    readonly clerk_id: string;
    watching_instruments?: Array<string>;
    readonly balance: string;
};

/**
 * Serializer for investor statistics data.
 */
export type InvestorStats = {
    /**
     * Today's gain in currency
     */
    todays_gain: number;
    /**
     * Total gain in currency
     */
    total_gain: number;
    /**
     * Total amount invested
     */
    invested: number;
    /**
     * Total account value
     */
    total_value: number;
};

export type InvestorUpdate = {
    readonly id: string;
    readonly clerk_id: string;
    /**
     * User's preferred language (e.g., 'en', 'pl')
     */
    language?: string;
    watching_instruments?: Array<string>;
};

export type InvestorUpdateRequest = {
    /**
     * User's preferred language (e.g., 'en', 'pl')
     */
    language?: string;
    watching_instruments?: Array<string>;
};

/**
 * * `en` - English
 * * `pl` - Polski
 */
export type LanguageEnum = 'en' | 'pl';

export type LanguageUpdate = {
    /**
     * Language code (e.g., 'en', 'pl')
     *
     * * `en` - English
     * * `pl` - Polski
     */
    language: LanguageEnum;
};

export type LanguageUpdateRequest = {
    /**
     * Language code (e.g., 'en', 'pl')
     *
     * * `en` - English
     * * `pl` - Polski
     */
    language: LanguageEnum;
};

/**
 * * `us` - United States
 * * `global` - Global
 */
export type LocaleEnum = 'us' | 'global';

export type MarketCurrencies = {
    crypto?: string | null;
    fx?: string | null;
};

/**
 * * `stocks` - Stocks
 * * `crypto` - Crypto
 * * `fx` - Foreign Exchange
 * * `otc` - Over-the-Counter
 * * `indices` - Indices
 */
export type MarketEnum = 'stocks' | 'crypto' | 'fx' | 'otc' | 'indices';

export type MarketExchanges = {
    nasdaq?: string | null;
    nyse?: string | null;
    otc?: string | null;
};

export type MarketHoliday = {
    close?: string | null;
    date?: string | null;
    exchange?: string | null;
    name?: string | null;
    open?: string | null;
    status?: string | null;
};

export type MarketIndices = {
    s_and_p?: string | null;
    societe_generale?: string | null;
    cgi?: string | null;
    msci?: string | null;
    ftse_russell?: string | null;
    mstar?: string | null;
    mstarc?: string | null;
    cccy?: string | null;
    nasdaq?: string | null;
    dow_jones?: string | null;
};

export type MarketOrder = {
    readonly detail_type: string;
    volume: string;
    volume_processed?: string;
    is_buy: boolean;
};

export type MarketStatus = {
    after_hours?: boolean | null;
    currencies?: MarketCurrencies | null;
    early_hours?: boolean | null;
    exchanges?: MarketExchanges | null;
    indicesGroups?: MarketIndices | null;
    market?: string | null;
    server_time?: string | null;
};

export type MostTradedItem = {
    symbol: string;
    no_trades: number;
    buys: number;
    sells: number;
    gain: number;
    gain_percentage: number;
};

export type NotificationConfig = {
    readonly id: string;
    /**
     * Send Email
     */
    is_email?: boolean;
    /**
     * Send Push
     */
    is_push?: boolean;
    /**
     * Send WebSocket
     */
    is_websocket?: boolean;
    is_active?: boolean;
    readonly created_at: string;
};

export type NotificationConfigCreate = {
    is_email: boolean;
    is_push: boolean;
    is_websocket: boolean;
};

export type NotificationConfigCreateRequest = {
    is_email: boolean;
    is_push: boolean;
    is_websocket: boolean;
};

export type NotificationConfigRequest = {
    /**
     * Send Email
     */
    is_email?: boolean;
    /**
     * Send Push
     */
    is_push?: boolean;
    /**
     * Send WebSocket
     */
    is_websocket?: boolean;
    is_active?: boolean;
};

export type Order = {
    readonly id: string;
    ticker: InstrumentName;
    detail_type: number;
    detail: OrderDetail;
};

export type OrderDetail = {
    detail_type: 'market';
} & MarketOrder;

export type OwnedShare = {
    name: string;
    symbol: string;
    volume: number;
    value: number;
    gain: number;
    gain_percentage: number | null;
};

export type PaginatedInstrumentListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<InstrumentList>;
};

export type PaginatedInstrumentWithPriceList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<InstrumentWithPrice>;
};

export type PaginatedOrderList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Order>;
};

export type PaginatedPriceAlertList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<PriceAlert>;
};

export type PatchedInvestorUpdateRequest = {
    /**
     * User's preferred language (e.g., 'en', 'pl')
     */
    language?: string;
    watching_instruments?: Array<string>;
};

export type PatchedPriceAlertRequest = {
    threshold_type?: ThresholdTypeEnum;
    threshold_value?: string;
    notification_config?: NotificationConfigRequest;
};

export type Position = {
    /**
     * Ticker symbol
     */
    symbol: string;
    /**
     * Instrument name
     */
    name: string;
    logo: string | null;
    /**
     * Total quantity of shares
     */
    quantity: number;
    /**
     * Current market value
     */
    market_value: number;
    /**
     * Total gain or loss
     */
    gain: number;
    /**
     * Total gain or loss percentage
     */
    gain_percentage: number | null;
    /**
     * Transaction history
     */
    history: Array<HistoryEntry>;
};

export type PriceAlert = {
    readonly id: string;
    readonly instrument_name: string;
    readonly instrument_ticker: string;
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfig;
};

export type PriceAlertCreate = {
    readonly id: string;
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigCreate;
};

export type PriceAlertCreateRequest = {
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigCreateRequest;
};

export type PriceAlertRequest = {
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigRequest;
};

export type PriceBar = {
    timestamp: string;
    open: string;
    high: string;
    low: string;
    close: string;
    volume: string;
    transactions?: number | null;
    volume_weighted_average_price?: string | null;
};

export type PriceDaily = {
    open: string;
    high: string;
    low: string;
    close: string;
    volume: string;
    volume_weighted_average_price: string;
};

export type PriceDailySummary = {
    ticker: string;
    current_price: string;
    daily_summary: PriceDaily;
    todays_change: string;
    todays_change_percent: string;
    last_updated: string;
};

export type Publisher = {
    favicon_url?: string | null;
    homepage_url?: string | null;
    logo_url?: string | null;
    name?: string | null;
};

export type PushNotificationRequest = {
    endpoint: string;
    p256dh: string;
    auth: string;
};

/**
 * Serializer for simple OK response
 */
export type SimpleResponse = {
    /**
     * Simple confirmation response
     */
    OK?: string;
};

/**
 * Serializer for status endpoint response
 */
export type StatusResponse = {
    /**
     * Status message indicating the application is running
     */
    message: string;
};

/**
 * * `above` - Above
 * * `below` - Below
 */
export type ThresholdTypeEnum = 'above' | 'below';

export type TickerNews = {
    amp_url?: string | null;
    article_url?: string | null;
    author?: string | null;
    description?: string | null;
    id?: string | null;
    image_url?: string | null;
    insights?: Array<Insight> | null;
    keywords?: Array<string> | null;
    published_utc?: string | null;
    publisher?: Publisher | null;
    tickers?: Array<string> | null;
    title?: string | null;
};

export type TradingOverview = {
    total_trades: number;
    buys: number;
    sells: number;
    total_gain: number;
};

export type VapidPublicKey = {
    public_key: string;
};

/**
 * Serializer for AccountValueSnapshot model.
 */
export type AccountValueSnapshotDailyWritable = {
    /**
     * Account value on this date
     */
    value: number;
};

export type InstrumentListWritable = {
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active: boolean;
    name: string;
    market: MarketEnum;
    market_cap?: string | null;
    currency_name: string;
    icon?: string | null;
    logo?: string | null;
};

export type InstrumentRetrieveWritable = {
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active: boolean;
    name: string;
    /**
     * Central Index Key assigned by the SEC.
     */
    cik?: string | null;
    market: MarketEnum;
    market_cap?: string | null;
    /**
     * Composite Financial Instrument Global Identifier.
     */
    composite_figi?: string | null;
    currency_name: string;
    /**
     * Locale where the ticker is traded, e.g. 'US'.
     *
     * * `us` - United States
     * * `global` - Global
     */
    locale: LocaleEnum;
    /**
     * Code of the primary exchange where the ticker is traded.
     */
    primary_exchange?: string | null;
    share_class_figi?: string | null;
    description?: string | null;
    /**
     * Base symbol for related tickers.
     */
    ticker_root?: string | null;
    /**
     * Suffix for ticker if applicable.
     */
    ticker_suffix?: string | null;
    homepage_url?: string | null;
    /**
     * Date when the ticker was first listed.
     */
    list_date?: string | null;
    phone_number?: string | null;
    /**
     * Shares Outstanding (Share Class)
     * Number of shares outstanding for this share class.
     */
    share_class_shares_outstanding?: number | null;
    /**
     * Standard Industrial Classification code.
     */
    sic_code?: string | null;
    sic_description?: string | null;
    total_employees?: number | null;
    weighted_shares_outstanding?: number | null;
    icon?: string | null;
    logo?: string | null;
};

export type InstrumentWithPriceWritable = {
    /**
     * Ticker Symbol
     */
    ticker: string;
    /**
     * Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.
     */
    type?: string | null;
    /**
     * Indicates whether the ticker is actively traded.
     */
    active: boolean;
    name: string;
    market: MarketEnum;
    market_cap?: string | null;
    currency_name: string;
    icon?: string | null;
    logo?: string | null;
};

export type InvestorWritable = {
    watching_instruments?: Array<string>;
};

export type InvestorUpdateWritable = {
    /**
     * User's preferred language (e.g., 'en', 'pl')
     */
    language?: string;
    watching_instruments?: Array<string>;
};

export type MarketOrderWritable = {
    volume: string;
    volume_processed?: string;
    is_buy: boolean;
};

export type NotificationConfigWritable = {
    /**
     * Send Email
     */
    is_email?: boolean;
    /**
     * Send Push
     */
    is_push?: boolean;
    /**
     * Send WebSocket
     */
    is_websocket?: boolean;
    is_active?: boolean;
};

export type NotificationConfigCreateRequestWritable = {
    is_email: boolean;
    is_push: boolean;
    is_websocket: boolean;
    push_subscription?: PushNotificationRequest;
};

export type OrderWritable = {
    ticker: InstrumentName;
    detail_type: number;
};

export type PriceAlertWritable = {
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigWritable;
};

export type PriceAlertCreateWritable = {
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigCreate;
};

export type PriceAlertCreateRequestWritable = {
    instrument_ticker: string;
    threshold_type: ThresholdTypeEnum;
    threshold_value: string;
    notification_config: NotificationConfigCreateRequestWritable;
};

export type AuthSignInCreateData = {
    body: ClerkLoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/sign-in/';
};

export type AuthSignInCreateErrors = {
    /**
     * Invalid credentials or user not found.
     */
    400: unknown;
    /**
     * Password verification failed.
     */
    401: unknown;
    /**
     * Clerk SDK error or other internal server error.
     */
    500: unknown;
};

export type AuthSignInCreateResponses = {
    /**
     * Sign-in successful, token returned.
     */
    200: unknown;
};

export type InstrumentsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/instruments/';
};

export type InstrumentsListResponses = {
    200: PaginatedInstrumentListList;
};

export type InstrumentsListResponse = InstrumentsListResponses[keyof InstrumentsListResponses];

export type InstrumentsDetailRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by cik.
         */
        cik?: string;
        /**
         * Filter by composite_figi.
         */
        composite_figi?: string;
        /**
         * Filter by id.
         */
        id?: string;
        /**
         * Filter by share_class_figi.
         */
        share_class_figi?: string;
        /**
         * Filter by ticker.
         */
        ticker?: string;
    };
    url: '/api/instruments/detail/';
};

export type InstrumentsDetailRetrieveResponses = {
    200: InstrumentRetrieve;
};

export type InstrumentsDetailRetrieveResponse = InstrumentsDetailRetrieveResponses[keyof InstrumentsDetailRetrieveResponses];

export type InstrumentsWithPricesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/instruments/with-prices/';
};

export type InstrumentsWithPricesListResponses = {
    200: PaginatedInstrumentWithPriceList;
};

export type InstrumentsWithPricesListResponse = InstrumentsWithPricesListResponses[keyof InstrumentsWithPricesListResponses];

export type InvestorsRetrieveData = {
    body?: never;
    path: {
        clerk_id: string;
    };
    query?: never;
    url: '/api/investors/{clerk_id}/';
};

export type InvestorsRetrieveResponses = {
    200: Investor;
};

export type InvestorsRetrieveResponse = InvestorsRetrieveResponses[keyof InvestorsRetrieveResponses];

export type InvestorsPartialUpdateData = {
    body?: PatchedInvestorUpdateRequest;
    path: {
        clerk_id: string;
    };
    query?: never;
    url: '/api/investors/{clerk_id}/';
};

export type InvestorsPartialUpdateResponses = {
    200: InvestorUpdate;
};

export type InvestorsPartialUpdateResponse = InvestorsPartialUpdateResponses[keyof InvestorsPartialUpdateResponses];

export type InvestorsUpdateData = {
    body?: InvestorUpdateRequest;
    path: {
        clerk_id: string;
    };
    query?: never;
    url: '/api/investors/{clerk_id}/';
};

export type InvestorsUpdateResponses = {
    200: InvestorUpdate;
};

export type InvestorsUpdateResponse = InvestorsUpdateResponses[keyof InvestorsUpdateResponses];

export type InvestorsMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/investors/me/';
};

export type InvestorsMeRetrieveResponses = {
    200: Investor;
};

export type InvestorsMeRetrieveResponse = InvestorsMeRetrieveResponses[keyof InvestorsMeRetrieveResponses];

export type InvestorsMeAccountValueListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/investors/me/account-value/';
};

export type InvestorsMeAccountValueListResponses = {
    200: Array<AccountValueSnapshotDaily>;
};

export type InvestorsMeAccountValueListResponse = InvestorsMeAccountValueListResponses[keyof InvestorsMeAccountValueListResponses];

export type InvestorsMeLanguageCreateData = {
    body: LanguageUpdateRequest;
    path?: never;
    query?: never;
    url: '/api/investors/me/language/';
};

export type InvestorsMeLanguageCreateResponses = {
    201: LanguageUpdate;
};

export type InvestorsMeLanguageCreateResponse = InvestorsMeLanguageCreateResponses[keyof InvestorsMeLanguageCreateResponses];

export type MarketsHolidaysListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/markets/holidays/';
};

export type MarketsHolidaysListResponses = {
    200: Array<MarketHoliday>;
};

export type MarketsHolidaysListResponse = MarketsHolidaysListResponses[keyof MarketsHolidaysListResponses];

export type MarketsStatusRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/markets/status/';
};

export type MarketsStatusRetrieveResponses = {
    200: MarketStatus;
};

export type MarketsStatusRetrieveResponse = MarketsStatusRetrieveResponses[keyof MarketsStatusRetrieveResponses];

export type NewsListData = {
    body?: never;
    path?: never;
    query?: {
        number_of_news?: number;
        /**
         * * `asc` - asc
         * * `desc` - desc
         */
        order?: 'asc' | 'desc';
        published_utc?: string;
        published_utc_gte?: string;
        published_utc_lte?: string;
        sort?: string;
        ticker?: string;
    };
    url: '/api/news/';
};

export type NewsListResponses = {
    200: Array<TickerNews>;
};

export type NewsListResponse = NewsListResponses[keyof NewsListResponses];

export type NotificationsVapidPublicKeyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/vapid-public-key/';
};

export type NotificationsVapidPublicKeyRetrieveResponses = {
    200: VapidPublicKey;
};

export type NotificationsVapidPublicKeyRetrieveResponse = NotificationsVapidPublicKeyRetrieveResponses[keyof NotificationsVapidPublicKeyRetrieveResponses];

export type OrdersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/api/orders/';
};

export type OrdersListResponses = {
    200: PaginatedOrderList;
};

export type OrdersListResponse = OrdersListResponses[keyof OrdersListResponses];

export type OrdersCancelDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/orders/cancel/{id}';
};

export type OrdersCancelDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OrdersCancelDestroyResponse = OrdersCancelDestroyResponses[keyof OrdersCancelDestroyResponses];

export type OrdersMarketCreateData = {
    body: CreateMarketOrderRequest;
    path?: never;
    query?: never;
    url: '/api/orders/market/';
};

export type OrdersMarketCreateResponses = {
    201: Order;
};

export type OrdersMarketCreateResponse = OrdersMarketCreateResponses[keyof OrdersMarketCreateResponses];

export type PricesListData = {
    body?: never;
    path?: never;
    query: {
        /**
         * List of ticker symbols to fetch prices for (max 50).
         */
        tickers: Array<string>;
    };
    url: '/api/prices/';
};

export type PricesListResponses = {
    200: PriceDailySummary;
};

export type PricesListResponse = PricesListResponses[keyof PricesListResponses];

export type PricesRetrieveData = {
    body?: never;
    path: {
        ticker: string;
    };
    query?: never;
    url: '/api/prices/{ticker}/';
};

export type PricesRetrieveResponses = {
    200: PriceDailySummary;
};

export type PricesRetrieveResponse = PricesRetrieveResponses[keyof PricesRetrieveResponses];

export type PricesBarsData = {
    body?: never;
    path?: never;
    query: {
        end_date?: string;
        /**
         * * `SECOND` - SECOND
         * * `MINUTE` - MINUTE
         * * `HOUR` - HOUR
         * * `DAY` - DAY
         * * `WEEK` - WEEK
         * * `MONTH` - MONTH
         * * `QUARTER` - QUARTER
         * * `YEAR` - YEAR
         */
        interval: 'SECOND' | 'MINUTE' | 'HOUR' | 'DAY' | 'WEEK' | 'MONTH' | 'QUARTER' | 'YEAR';
        interval_multiplier?: number;
        start_date: string;
        ticker: string;
    };
    url: '/api/prices/bars/';
};

export type PricesBarsResponses = {
    200: Array<PriceBar>;
};

export type PricesBarsResponse = PricesBarsResponses[keyof PricesBarsResponses];

export type PricesPriceAlertListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/api/prices/price-alert/';
};

export type PricesPriceAlertListResponses = {
    200: PaginatedPriceAlertList;
};

export type PricesPriceAlertListResponse = PricesPriceAlertListResponses[keyof PricesPriceAlertListResponses];

export type PricesPriceAlertCreateData = {
    body: PriceAlertCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/prices/price-alert/';
};

export type PricesPriceAlertCreateResponses = {
    201: PriceAlertCreate;
};

export type PricesPriceAlertCreateResponse = PricesPriceAlertCreateResponses[keyof PricesPriceAlertCreateResponses];

export type PricesPriceAlertDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/prices/price-alert/{id}/';
};

export type PricesPriceAlertDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type PricesPriceAlertDestroyResponse = PricesPriceAlertDestroyResponses[keyof PricesPriceAlertDestroyResponses];

export type PricesPriceAlertRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/prices/price-alert/{id}/';
};

export type PricesPriceAlertRetrieveResponses = {
    200: PriceAlert;
};

export type PricesPriceAlertRetrieveResponse = PricesPriceAlertRetrieveResponses[keyof PricesPriceAlertRetrieveResponses];

export type PricesPriceAlertPartialUpdateData = {
    body?: PatchedPriceAlertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/prices/price-alert/{id}/';
};

export type PricesPriceAlertPartialUpdateResponses = {
    200: PriceAlert;
};

export type PricesPriceAlertPartialUpdateResponse = PricesPriceAlertPartialUpdateResponses[keyof PricesPriceAlertPartialUpdateResponses];

export type PricesPriceAlertUpdateData = {
    body: PriceAlertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/prices/price-alert/{id}/';
};

export type PricesPriceAlertUpdateResponses = {
    200: PriceAlert;
};

export type PricesPriceAlertUpdateResponse = PricesPriceAlertUpdateResponses[keyof PricesPriceAlertUpdateResponses];

export type StatisticsAssetAllocationRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/asset-allocation/';
};

export type StatisticsAssetAllocationRetrieveResponses = {
    200: AssetAllocation;
};

export type StatisticsAssetAllocationRetrieveResponse = StatisticsAssetAllocationRetrieveResponses[keyof StatisticsAssetAllocationRetrieveResponses];

export type StatisticsCurrentAccountValueRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/current-account-value/';
};

export type StatisticsCurrentAccountValueRetrieveResponses = {
    200: CurrentAccountValue;
};

export type StatisticsCurrentAccountValueRetrieveResponse = StatisticsCurrentAccountValueRetrieveResponses[keyof StatisticsCurrentAccountValueRetrieveResponses];

export type StatisticsOwnedSharesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/owned-shares/';
};

export type StatisticsOwnedSharesListResponses = {
    200: Array<OwnedShare>;
};

export type StatisticsOwnedSharesListResponse = StatisticsOwnedSharesListResponses[keyof StatisticsOwnedSharesListResponses];

export type StatisticsStatisticsMostTradedListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/statistics/most-traded/';
};

export type StatisticsStatisticsMostTradedListResponses = {
    200: Array<MostTradedItem>;
};

export type StatisticsStatisticsMostTradedListResponse = StatisticsStatisticsMostTradedListResponses[keyof StatisticsStatisticsMostTradedListResponses];

export type StatisticsStatisticsTradingOverviewRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/statistics/trading-overview/';
};

export type StatisticsStatisticsTradingOverviewRetrieveResponses = {
    200: TradingOverview;
};

export type StatisticsStatisticsTradingOverviewRetrieveResponse = StatisticsStatisticsTradingOverviewRetrieveResponses[keyof StatisticsStatisticsTradingOverviewRetrieveResponses];

export type StatisticsStatsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statistics/stats/';
};

export type StatisticsStatsRetrieveResponses = {
    200: InvestorStats;
};

export type StatisticsStatsRetrieveResponse = StatisticsStatsRetrieveResponses[keyof StatisticsStatsRetrieveResponses];

export type StatisticsTransactionsHistoryListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * List of ticker symbols to fetch prices for (max 50).
         */
        tickers?: Array<string>;
        /**
         * Type of positions to fetch: 'open', 'closed', or 'both'
         *
         * * `open` - open
         * * `closed` - closed
         * * `both` - both
         */
        type?: 'open' | 'closed' | 'both';
    };
    url: '/api/statistics/transactions-history/';
};

export type StatisticsTransactionsHistoryListResponses = {
    200: Array<Position>;
};

export type StatisticsTransactionsHistoryListResponse = StatisticsTransactionsHistoryListResponses[keyof StatisticsTransactionsHistoryListResponses];

export type StatusRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status/';
};

export type StatusRetrieveResponses = {
    /**
     * Application status
     */
    200: StatusResponse;
};

export type StatusRetrieveResponse = StatusRetrieveResponses[keyof StatusRetrieveResponses];

export type TestAdminTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/admin_test/';
};

export type TestAdminTestRetrieveResponses = {
    /**
     * Admin authentication test successful
     */
    200: AuthTestResponse;
};

export type TestAdminTestRetrieveResponse = TestAdminTestRetrieveResponses[keyof TestAdminTestRetrieveResponses];

export type TestAllTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/all_test/';
};

export type TestAllTestRetrieveResponses = {
    /**
     * Unauthenticated test successful
     */
    200: SimpleResponse;
};

export type TestAllTestRetrieveResponse = TestAllTestRetrieveResponses[keyof TestAllTestRetrieveResponses];

export type TestAlpacaTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/alpaca_test/';
};

export type TestAlpacaTestRetrieveResponses = {
    /**
     * Last trade result from Alpaca
     */
    200: SimpleResponse;
};

export type TestAlpacaTestRetrieveResponse = TestAlpacaTestRetrieveResponses[keyof TestAlpacaTestRetrieveResponses];

export type TestPolygonTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/polygon_test/';
};

export type TestPolygonTestRetrieveResponses = {
    /**
     * Last trade result from Polygon
     */
    200: SimpleResponse;
};

export type TestPolygonTestRetrieveResponse = TestPolygonTestRetrieveResponses[keyof TestPolygonTestRetrieveResponses];

export type TestUsersTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/users_test/';
};

export type TestUsersTestRetrieveResponses = {
    /**
     * Authentication test successful
     */
    200: AuthTestResponse;
};

export type TestUsersTestRetrieveResponse = TestUsersTestRetrieveResponses[keyof TestUsersTestRetrieveResponses];
