// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Serializer for AccountValueSnapshot model.
 */
export const zAccountValueSnapshotDaily = z.object({
    date: z.iso.date().readonly(),
    value: z.number()
});

export const zAssetAllocationItem = z.object({
    instrument_name: z.string().max(255),
    instrument_ticker: z.string().max(20),
    instrument_logo: z.union([
        z.url(),
        z.null()
    ]),
    instrument_icon: z.union([
        z.url(),
        z.null()
    ]),
    value: z.number(),
    percentage: z.number()
});

export const zAssetAllocation = z.object({
    total_value: z.number(),
    total_gain_this_year: z.number(),
    allocations: z.array(zAssetAllocationItem)
});

/**
 * Serializer for authentication test response
 */
export const zAuthTestResponse = z.object({
    message: z.string(),
    user_role: z.string(),
    user_id: z.int()
});

export const zClerkLoginRequest = z.object({
    email: z.email().min(1),
    password: z.string().min(1)
});

export const zCreateMarketOrder = z.object({
    id: z.uuid().readonly(),
    investor: z.uuid().readonly()
});

export const zCreateMarketOrderRequest = z.object({
    ticker: z.string().min(1),
    volume: z.string().regex(/^-?\d{0,13}(?:\.\d{0,2})?$/),
    is_buy: z.boolean()
});

export const zCurrentAccountValue = z.object({
    total_account_value: z.number(),
    gain: z.number(),
    gain_percentage: z.union([
        z.number(),
        z.null()
    ])
});

export const zHistoryEntry = z.object({
    timestamp: z.iso.datetime({
        offset: true
    }),
    is_buy: z.boolean(),
    quantity: z.int(),
    share_price: z.number(),
    acquisition_price: z.union([
        z.number(),
        z.null()
    ])
});

export const zInsight = z.object({
    sentiment: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    sentiment_reasoning: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ticker: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * * `stocks` - Stocks
 * * `crypto` - Crypto
 * * `fx` - Foreign Exchange
 * * `otc` - Over-the-Counter
 * * `indices` - Indices
 */
export const zMarketEnum = z.enum([
    'stocks',
    'crypto',
    'fx',
    'otc',
    'indices'
]);

export const zInstrumentList = z.object({
    id: z.uuid().readonly(),
    ticker: z.string().max(20),
    type: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    active: z.boolean(),
    name: z.string().max(255),
    market: zMarketEnum,
    market_cap: z.optional(z.union([
        z.string().regex(/^-?\d{0,18}(?:\.\d{0,2})?$/),
        z.null()
    ])),
    currency_name: z.string().max(50),
    icon: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    logo: z.optional(z.union([
        z.url(),
        z.null()
    ]))
});

export const zInstrumentName = z.object({
    ticker: z.string().max(20)
});

/**
 * * `us` - United States
 * * `global` - Global
 */
export const zLocaleEnum = z.enum([
    'us',
    'global'
]);

export const zInstrumentRetrieve = z.object({
    id: z.uuid().readonly(),
    ticker: z.string().max(20),
    type: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    active: z.boolean(),
    name: z.string().max(255),
    cik: z.optional(z.union([
        z.string().max(20),
        z.null()
    ])),
    market: zMarketEnum,
    market_cap: z.optional(z.union([
        z.string().regex(/^-?\d{0,18}(?:\.\d{0,2})?$/),
        z.null()
    ])),
    composite_figi: z.optional(z.union([
        z.string().max(20),
        z.null()
    ])),
    currency_name: z.string().max(50),
    locale: zLocaleEnum,
    primary_exchange: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    share_class_figi: z.optional(z.union([
        z.string().max(20),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ticker_root: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    ticker_suffix: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    homepage_url: z.optional(z.union([
        z.url().max(200),
        z.null()
    ])),
    list_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    phone_number: z.optional(z.union([
        z.string().max(30),
        z.null()
    ])),
    share_class_shares_outstanding: z.optional(z.union([
        z.coerce.bigint().gte(BigInt(-9223372036854776000)).lte(BigInt(9223372036854776000)),
        z.null()
    ])),
    sic_code: z.optional(z.union([
        z.string().max(10),
        z.null()
    ])),
    sic_description: z.optional(z.union([
        z.string().max(255),
        z.null()
    ])),
    total_employees: z.optional(z.union([
        z.int().gte(-2147483648).lte(2147483647),
        z.null()
    ])),
    weighted_shares_outstanding: z.optional(z.union([
        z.coerce.bigint().gte(BigInt(-9223372036854776000)).lte(BigInt(9223372036854776000)),
        z.null()
    ])),
    address: z.object({
        address1: z.union([
            z.string(),
            z.null()
        ]),
        address2: z.union([
            z.string(),
            z.null()
        ]),
        city: z.union([
            z.string(),
            z.null()
        ]),
        state: z.union([
            z.string(),
            z.null()
        ]),
        postal_code: z.union([
            z.string(),
            z.null()
        ])
    }).readonly(),
    icon: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    logo: z.optional(z.union([
        z.url(),
        z.null()
    ]))
});

export const zPriceDaily = z.object({
    open: z.string(),
    high: z.string(),
    low: z.string(),
    close: z.string(),
    volume: z.string(),
    volume_weighted_average_price: z.string()
});

export const zPriceDailySummary = z.object({
    ticker: z.string(),
    current_price: z.string(),
    daily_summary: zPriceDaily,
    todays_change: z.string(),
    todays_change_percent: z.string(),
    last_updated: z.iso.datetime({
        offset: true
    })
});

export const zInstrumentWithPrice = z.object({
    id: z.uuid().readonly(),
    ticker: z.string().max(20),
    type: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    active: z.boolean(),
    name: z.string().max(255),
    market: zMarketEnum,
    market_cap: z.optional(z.union([
        z.string().regex(/^-?\d{0,18}(?:\.\d{0,2})?$/),
        z.null()
    ])),
    currency_name: z.string().max(50),
    icon: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    logo: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    price_info: zPriceDailySummary
});

export const zInvestor = z.object({
    id: z.uuid().readonly(),
    clerk_id: z.string().readonly(),
    watching_instruments: z.optional(z.array(z.uuid()))
});

/**
 * Serializer for investor statistics data.
 */
export const zInvestorStats = z.object({
    todays_gain: z.number(),
    total_gain: z.number(),
    invested: z.number(),
    total_value: z.number()
});

export const zInvestorUpdate = z.object({
    id: z.uuid().readonly(),
    clerk_id: z.string().readonly(),
    language: z.optional(z.string().max(10)),
    watching_instruments: z.optional(z.array(z.uuid()))
});

export const zInvestorUpdateRequest = z.object({
    language: z.optional(z.string().min(1).max(10)),
    watching_instruments: z.optional(z.array(z.uuid()))
});

export const zMarketCurrencies = z.object({
    crypto: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    fx: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zMarketExchanges = z.object({
    nasdaq: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    nyse: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    otc: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zMarketHoliday = z.object({
    close: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    date: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    exchange: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    open: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zMarketIndices = z.object({
    s_and_p: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    societe_generale: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cgi: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    msci: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ftse_russell: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    mstar: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    mstarc: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    cccy: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    nasdaq: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    dow_jones: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zMarketOrder = z.object({
    volume: z.string().regex(/^-?\d{0,13}(?:\.\d{0,2})?$/),
    volume_processed: z.optional(z.string().regex(/^-?\d{0,13}(?:\.\d{0,2})?$/)),
    is_buy: z.boolean()
});

export const zMarketStatus = z.object({
    after_hours: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    currencies: z.optional(z.union([
        zMarketCurrencies,
        z.null()
    ])),
    early_hours: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    exchanges: z.optional(z.union([
        zMarketExchanges,
        z.null()
    ])),
    indicesGroups: z.optional(z.union([
        zMarketIndices,
        z.null()
    ])),
    market: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    server_time: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zMostTradedItem = z.object({
    symbol: z.string().max(10),
    no_trades: z.int(),
    buys: z.int(),
    sells: z.int(),
    gain: z.number(),
    gain_percentage: z.number()
});

export const zNotificationConfig = z.object({
    id: z.uuid().readonly(),
    is_email: z.optional(z.boolean()),
    is_push: z.optional(z.boolean()),
    is_websocket: z.optional(z.boolean()),
    is_active: z.optional(z.boolean()),
    created_at: z.iso.datetime({
        offset: true
    }).readonly()
});

export const zNotificationConfigCreate = z.object({
    is_email: z.boolean(),
    is_push: z.boolean(),
    is_websocket: z.boolean()
});

export const zNotificationConfigCreateRequest = z.object({
    is_email: z.boolean(),
    is_push: z.boolean(),
    is_websocket: z.boolean()
});

export const zNotificationConfigRequest = z.object({
    is_email: z.optional(z.boolean()),
    is_push: z.optional(z.boolean()),
    is_websocket: z.optional(z.boolean()),
    is_active: z.optional(z.boolean())
});

export const zOrderDetail = z.object({
    detail_type: z.literal('market')
}).and(zMarketOrder);

export const zOrder = z.object({
    id: z.uuid().readonly(),
    ticker: zInstrumentName,
    detail_type: z.int(),
    detail: zOrderDetail
});

export const zOwnedShare = z.object({
    name: z.string().max(100),
    symbol: z.string().max(10),
    volume: z.number(),
    value: z.number(),
    gain: z.number(),
    gain_percentage: z.union([
        z.number(),
        z.null()
    ])
});

export const zPaginatedInstrumentListList = z.object({
    count: z.int(),
    next: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    previous: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    results: z.array(zInstrumentList)
});

export const zPaginatedInstrumentWithPriceList = z.object({
    count: z.int(),
    next: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    previous: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    results: z.array(zInstrumentWithPrice)
});

export const zPaginatedOrderList = z.object({
    count: z.int(),
    next: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    previous: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    results: z.array(zOrder)
});

/**
 * * `above` - Above
 * * `below` - Below
 */
export const zThresholdTypeEnum = z.enum([
    'above',
    'below'
]);

export const zPriceAlert = z.object({
    id: z.uuid().readonly(),
    instrument_name: z.string().readonly(),
    instrument_ticker: z.string().readonly(),
    threshold_type: zThresholdTypeEnum,
    threshold_value: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    notification_config: zNotificationConfig
});

export const zPaginatedPriceAlertList = z.object({
    count: z.int(),
    next: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    previous: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    results: z.array(zPriceAlert)
});

export const zPatchedInvestorUpdateRequest = z.object({
    language: z.optional(z.string().min(1).max(10)),
    watching_instruments: z.optional(z.array(z.uuid()))
});

export const zPatchedPriceAlertRequest = z.object({
    threshold_type: z.optional(zThresholdTypeEnum),
    threshold_value: z.optional(z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/)),
    notification_config: z.optional(zNotificationConfigRequest)
});

export const zPosition = z.object({
    name: z.string().max(10),
    quantity: z.int(),
    market_value: z.number(),
    gain: z.number(),
    gain_percentage: z.number(),
    history: z.array(zHistoryEntry)
});

export const zPriceAlertCreate = z.object({
    id: z.uuid().readonly(),
    threshold_type: zThresholdTypeEnum,
    threshold_value: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    notification_config: zNotificationConfigCreate
});

export const zPriceAlertCreateRequest = z.object({
    threshold_type: zThresholdTypeEnum,
    threshold_value: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    notification_config: zNotificationConfigCreateRequest
});

export const zPriceAlertRequest = z.object({
    threshold_type: zThresholdTypeEnum,
    threshold_value: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    notification_config: zNotificationConfigRequest
});

export const zPriceBar = z.object({
    timestamp: z.iso.datetime({
        offset: true
    }),
    open: z.string(),
    high: z.string(),
    low: z.string(),
    close: z.string(),
    volume: z.string(),
    transactions: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    volume_weighted_average_price: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zPublisher = z.object({
    favicon_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    homepage_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    logo_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zPushNotificationRequest = z.object({
    endpoint: z.url().min(1),
    p256dh: z.string().min(1).max(255),
    auth: z.string().min(1).max(255)
});

/**
 * Serializer for simple OK response
 */
export const zSimpleResponse = z.object({
    OK: z.optional(z.string()).default('OK')
});

/**
 * Serializer for status endpoint response
 */
export const zStatusResponse = z.object({
    message: z.string()
});

export const zTickerNews = z.object({
    amp_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    article_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    author: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    image_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    insights: z.optional(z.union([
        z.array(zInsight),
        z.null()
    ])),
    keywords: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    published_utc: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    publisher: z.optional(z.union([
        zPublisher,
        z.null()
    ])),
    tickers: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zTradingOverview = z.object({
    total_trades: z.int(),
    buys: z.int(),
    sells: z.int(),
    total_gain: z.number()
});

export const zVapidPublicKey = z.object({
    public_key: z.string()
});

/**
 * Serializer for AccountValueSnapshot model.
 */
export const zAccountValueSnapshotDailyWritable = z.object({
    value: z.number()
});

export const zInstrumentListWritable = z.object({
    ticker: z.string().max(20),
    type: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    active: z.boolean(),
    name: z.string().max(255),
    market: zMarketEnum,
    market_cap: z.optional(z.union([
        z.string().regex(/^-?\d{0,18}(?:\.\d{0,2})?$/),
        z.null()
    ])),
    currency_name: z.string().max(50),
    icon: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    logo: z.optional(z.union([
        z.url(),
        z.null()
    ]))
});

export const zInstrumentRetrieveWritable = z.object({
    ticker: z.string().max(20),
    type: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    active: z.boolean(),
    name: z.string().max(255),
    cik: z.optional(z.union([
        z.string().max(20),
        z.null()
    ])),
    market: zMarketEnum,
    market_cap: z.optional(z.union([
        z.string().regex(/^-?\d{0,18}(?:\.\d{0,2})?$/),
        z.null()
    ])),
    composite_figi: z.optional(z.union([
        z.string().max(20),
        z.null()
    ])),
    currency_name: z.string().max(50),
    locale: zLocaleEnum,
    primary_exchange: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    share_class_figi: z.optional(z.union([
        z.string().max(20),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ticker_root: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    ticker_suffix: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    homepage_url: z.optional(z.union([
        z.url().max(200),
        z.null()
    ])),
    list_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    phone_number: z.optional(z.union([
        z.string().max(30),
        z.null()
    ])),
    share_class_shares_outstanding: z.optional(z.union([
        z.coerce.bigint().gte(BigInt(-9223372036854776000)).lte(BigInt(9223372036854776000)),
        z.null()
    ])),
    sic_code: z.optional(z.union([
        z.string().max(10),
        z.null()
    ])),
    sic_description: z.optional(z.union([
        z.string().max(255),
        z.null()
    ])),
    total_employees: z.optional(z.union([
        z.int().gte(-2147483648).lte(2147483647),
        z.null()
    ])),
    weighted_shares_outstanding: z.optional(z.union([
        z.coerce.bigint().gte(BigInt(-9223372036854776000)).lte(BigInt(9223372036854776000)),
        z.null()
    ])),
    icon: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    logo: z.optional(z.union([
        z.url(),
        z.null()
    ]))
});

export const zInstrumentWithPriceWritable = z.object({
    ticker: z.string().max(20),
    type: z.optional(z.union([
        z.string().max(50),
        z.null()
    ])),
    active: z.boolean(),
    name: z.string().max(255),
    market: zMarketEnum,
    market_cap: z.optional(z.union([
        z.string().regex(/^-?\d{0,18}(?:\.\d{0,2})?$/),
        z.null()
    ])),
    currency_name: z.string().max(50),
    icon: z.optional(z.union([
        z.url(),
        z.null()
    ])),
    logo: z.optional(z.union([
        z.url(),
        z.null()
    ]))
});

export const zInvestorWritable = z.object({
    watching_instruments: z.optional(z.array(z.uuid()))
});

export const zInvestorUpdateWritable = z.object({
    language: z.optional(z.string().max(10)),
    watching_instruments: z.optional(z.array(z.uuid()))
});

export const zNotificationConfigWritable = z.object({
    is_email: z.optional(z.boolean()),
    is_push: z.optional(z.boolean()),
    is_websocket: z.optional(z.boolean()),
    is_active: z.optional(z.boolean())
});

export const zNotificationConfigCreateRequestWritable = z.object({
    is_email: z.boolean(),
    is_push: z.boolean(),
    is_websocket: z.boolean(),
    push_subscription: z.optional(zPushNotificationRequest)
});

export const zOrderWritable = z.object({
    ticker: zInstrumentName,
    detail_type: z.int()
});

export const zPriceAlertWritable = z.object({
    threshold_type: zThresholdTypeEnum,
    threshold_value: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    notification_config: zNotificationConfigWritable
});

export const zPriceAlertCreateWritable = z.object({
    threshold_type: zThresholdTypeEnum,
    threshold_value: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    notification_config: zNotificationConfigCreate
});

export const zPriceAlertCreateRequestWritable = z.object({
    instrument_ticker: z.string().min(1),
    threshold_type: zThresholdTypeEnum,
    threshold_value: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    notification_config: zNotificationConfigCreateRequestWritable
});

export const zAuthSignInCreateData = z.object({
    body: zClerkLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zInstrumentsListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        ordering: z.optional(z.string()),
        page: z.optional(z.int()),
        page_size: z.optional(z.int()),
        search: z.optional(z.string())
    }))
});

export const zInstrumentsListResponse = zPaginatedInstrumentListList;

export const zInstrumentsDetailRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        cik: z.optional(z.string()),
        composite_figi: z.optional(z.string()),
        id: z.optional(z.string()),
        share_class_figi: z.optional(z.string()),
        ticker: z.optional(z.string())
    }))
});

export const zInstrumentsDetailRetrieveResponse = zInstrumentRetrieve;

export const zInstrumentsWithPricesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        ordering: z.optional(z.string()),
        page: z.optional(z.int()),
        page_size: z.optional(z.int()),
        search: z.optional(z.string())
    }))
});

export const zInstrumentsWithPricesListResponse = zPaginatedInstrumentWithPriceList;

export const zInvestorsRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        clerk_id: z.string()
    }),
    query: z.optional(z.never())
});

export const zInvestorsRetrieveResponse = zInvestor;

export const zInvestorsPartialUpdateData = z.object({
    body: z.optional(zPatchedInvestorUpdateRequest),
    path: z.object({
        clerk_id: z.string()
    }),
    query: z.optional(z.never())
});

export const zInvestorsPartialUpdateResponse = zInvestorUpdate;

export const zInvestorsUpdateData = z.object({
    body: z.optional(zInvestorUpdateRequest),
    path: z.object({
        clerk_id: z.string()
    }),
    query: z.optional(z.never())
});

export const zInvestorsUpdateResponse = zInvestorUpdate;

export const zInvestorsMeRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zInvestorsMeRetrieveResponse = zInvestor;

export const zInvestorsMeAccountValueListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zInvestorsMeAccountValueListResponse = z.array(zAccountValueSnapshotDaily);

export const zMarketsHolidaysListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zMarketsHolidaysListResponse = z.array(zMarketHoliday);

export const zMarketsStatusRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zMarketsStatusRetrieveResponse = zMarketStatus;

export const zNewsListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        number_of_news: z.optional(z.int().gte(1).lte(100)).default(30),
        order: z.optional(z.enum([
            'asc',
            'desc'
        ])),
        published_utc: z.optional(z.iso.datetime({
            offset: true
        })),
        published_utc_gte: z.optional(z.iso.datetime({
            offset: true
        })),
        published_utc_lte: z.optional(z.iso.datetime({
            offset: true
        })),
        sort: z.optional(z.string().min(1)).default('published_utc'),
        ticker: z.optional(z.string())
    }))
});

export const zNewsListResponse = z.array(zTickerNews);

export const zNotificationsVapidPublicKeyRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zNotificationsVapidPublicKeyRetrieveResponse = zVapidPublicKey;

export const zOrdersListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int()),
        page_size: z.optional(z.int())
    }))
});

export const zOrdersListResponse = zPaginatedOrderList;

export const zOrdersCancelDestroyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * No response body
 */
export const zOrdersCancelDestroyResponse = z.void();

export const zOrdersMarketCreateData = z.object({
    body: zCreateMarketOrderRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zOrdersMarketCreateResponse = zCreateMarketOrder;

export const zPricesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        tickers: z.array(z.string().min(1)).max(50)
    })
});

export const zPricesListResponse = zPriceDailySummary;

export const zPricesRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        ticker: z.string()
    }),
    query: z.optional(z.never())
});

export const zPricesRetrieveResponse = zPriceDailySummary;

export const zPricesBarsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        end_date: z.optional(z.iso.datetime({
            offset: true
        })).default('2025-09-23T00:00:00Z'),
        interval: z.enum([
            'SECOND',
            'MINUTE',
            'HOUR',
            'DAY',
            'WEEK',
            'MONTH',
            'QUARTER',
            'YEAR'
        ]),
        interval_multiplier: z.optional(z.int().gte(1)).default(1),
        start_date: z.iso.datetime({
            offset: true
        }),
        ticker: z.string().min(1).max(6)
    })
});

export const zPricesBarsResponse = z.array(zPriceBar);

export const zPricesPriceAlertListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int()),
        page_size: z.optional(z.int())
    }))
});

export const zPricesPriceAlertListResponse = zPaginatedPriceAlertList;

export const zPricesPriceAlertCreateData = z.object({
    body: zPriceAlertCreateRequestWritable,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPricesPriceAlertCreateResponse = zPriceAlertCreate;

export const zPricesPriceAlertDestroyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * No response body
 */
export const zPricesPriceAlertDestroyResponse = z.void();

export const zPricesPriceAlertRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zPricesPriceAlertRetrieveResponse = zPriceAlert;

export const zPricesPriceAlertPartialUpdateData = z.object({
    body: z.optional(zPatchedPriceAlertRequest),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zPricesPriceAlertPartialUpdateResponse = zPriceAlert;

export const zPricesPriceAlertUpdateData = z.object({
    body: zPriceAlertRequest,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zPricesPriceAlertUpdateResponse = zPriceAlert;

export const zStatisticsAssetAllocationRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zStatisticsAssetAllocationRetrieveResponse = zAssetAllocation;

export const zStatisticsCurrentAccountValueRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zStatisticsCurrentAccountValueRetrieveResponse = zCurrentAccountValue;

export const zStatisticsOwnedSharesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zStatisticsOwnedSharesListResponse = z.array(zOwnedShare);

export const zStatisticsStatisticsMostTradedListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zStatisticsStatisticsMostTradedListResponse = z.array(zMostTradedItem);

export const zStatisticsStatisticsTradingOverviewRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zStatisticsStatisticsTradingOverviewRetrieveResponse = zTradingOverview;

export const zStatisticsStatsRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zStatisticsStatsRetrieveResponse = zInvestorStats;

export const zStatisticsTransactionsHistoryListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        tickers: z.optional(z.array(z.string().min(1)).max(50)),
        type: z.optional(z.enum([
            'open',
            'closed',
            'both'
        ]))
    }))
});

export const zStatisticsTransactionsHistoryListResponse = z.array(zPosition);

export const zStatusRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Application status
 */
export const zStatusRetrieveResponse = zStatusResponse;

export const zTestAdminTestRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Admin authentication test successful
 */
export const zTestAdminTestRetrieveResponse = zAuthTestResponse;

export const zTestAllTestRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Unauthenticated test successful
 */
export const zTestAllTestRetrieveResponse = zSimpleResponse;

export const zTestAlpacaTestRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Last trade result from Alpaca
 */
export const zTestAlpacaTestRetrieveResponse = zSimpleResponse;

export const zTestPolygonTestRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Last trade result from Polygon
 */
export const zTestPolygonTestRetrieveResponse = zSimpleResponse;

export const zTestUsersTestRetrieveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Authentication test successful
 */
export const zTestUsersTestRetrieveResponse = zAuthTestResponse;
